# EE333 - Lab 7

#### Importing Libraries

In [1]:
import numpy as np
from scipy.linalg import null_space
import matplotlib.pyplot as plt

## Q1. Generate a real valued random fat matrix A of order (16×64), and a random vector b ∈ R16, use to method of least squares to solve for x if Ax = b.

In [2]:
A = np.random.randint(-100, 100, (16,64))
b = np.random.randint(-100, 100, (16,1))

In [3]:
def lstsq(A, b):
#     return ((np.linalg.inv((A.T.dot(A)))).dot(A.T)).dot(b)
    return (np.linalg.pinv(A)).dot(b)

In [4]:
x = lstsq(A, b)
x

array([[-0.10069924],
       [-0.0786966 ],
       [ 0.00877391],
       [ 0.10790735],
       [-0.07887201],
       [ 0.05094322],
       [-0.11680034],
       [ 0.04839814],
       [-0.013759  ],
       [ 0.08278285],
       [-0.20123177],
       [ 0.01376611],
       [ 0.06488676],
       [-0.07988768],
       [-0.09955084],
       [ 0.11853607],
       [-0.0330163 ],
       [-0.04642724],
       [-0.00111646],
       [ 0.00498479],
       [-0.08254294],
       [ 0.04139374],
       [-0.03388528],
       [-0.13074118],
       [ 0.04002906],
       [ 0.0037141 ],
       [-0.03306201],
       [ 0.02623061],
       [ 0.0479991 ],
       [-0.06079955],
       [ 0.00074043],
       [-0.03758906],
       [-0.05122024],
       [ 0.13556317],
       [ 0.01837257],
       [-0.0487731 ],
       [ 0.02512704],
       [-0.03484628],
       [ 0.03951385],
       [ 0.02211198],
       [ 0.07367149],
       [ 0.010315  ],
       [-0.03828631],
       [ 0.03612234],
       [-0.06640383],
       [ 0

## Q2. Generate an arbitrary vector z ∈ R64 such that no more than 6 of its entries are nonzero. Use this vector to generate the vector d = Az. Now solve for x in Ax = d. Is x = z?

In [5]:
z = np.zeros((64,1))
ind = np.random.randint(0,64,6)
for i in ind:
    z[i] = np.random.randint(-100,100)
z

array([[  0.],
       [  0.],
       [-55.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [-74.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [-84.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [ 17.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [ 99.],
       [  0.],
       [ -2.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.]])

In [6]:
d = A.dot(z)
xt = lstsq(A, d)
xt

array([[ -3.06876871],
       [ -1.64017108],
       [-10.75996157],
       [ 18.09560334],
       [ -1.45500953],
       [  4.65708507],
       [  4.75756746],
       [ 11.74797757],
       [-11.47681501],
       [  2.04927463],
       [ -0.61089086],
       [ -0.23152957],
       [-13.10858827],
       [-12.0282024 ],
       [ 13.85406077],
       [-11.13672623],
       [  5.59438268],
       [-29.49472947],
       [-16.43979   ],
       [ -5.20067478],
       [  8.5695902 ],
       [  4.94339683],
       [  7.68190082],
       [-14.78670626],
       [-15.76193017],
       [  7.26013848],
       [  8.14363216],
       [  5.61298287],
       [-10.66794909],
       [ 13.86570821],
       [ 16.95186701],
       [-12.6845995 ],
       [ 10.05532255],
       [-12.55479569],
       [  6.25291646],
       [ -3.07270594],
       [-16.58888831],
       [ -1.17176535],
       [  2.94037952],
       [  6.44265557],
       [  1.9667206 ],
       [  0.63661957],
       [  3.98517967],
       [  1

In [7]:
all(xt == z)

False

## Q3. Find the basis of the nullspace of A, and for any vector c ∈ Null(A), define y = x + c, and obtain the vector b' = Ay for multiple values of c. If Ay satisfies Ax = b, ∀c ∈ Null(A), then what is special about the case when c = 0.

In [8]:
nullA = null_space(A)

In [9]:
areEqual = np.zeros(nullA.shape[1])
for i,c in enumerate(nullA.T):
    y = x + c
    b_prime = A.dot(y)
    areEqual[i] = b_prime.all() == b.all()

areEqual.all()

True

## Q4. Look up the Orthogonal matching persuit (OMP) algorithm, and use that to recover x.

In [10]:
maxit = A.shape[1]
epsilon = 1e-3

In [11]:
def OMP(A, b, maxit, epsilon):
#     A_hat = A
#     b_hat = b
    A_hat = A / np.linalg.norm(A, 2, axis=0)
    b_hat = b / np.linalg.norm(b, 2)
    x = np.zeros(A.shape[1])
    residual = b_hat
    indices = []
    augmentedA = []
    for k in range(maxit):
        x = np.zeros(A.shape[1])
        indk = np.argmax(np.abs(A_hat.T.dot(residual)))
        indices.append(indk)
        augmentedA.append(A_hat[:,indices[k]])
        Ak = np.array(augmentedA).T
        xk = lstsq(Ak, b_hat)
        residualnew = b - Ak.dot(xk)
        for i in range(k):
            x[indices[i]] = xk[i]
        if np.linalg.norm((residualnew-residual), 2) < epsilon:
            break
    return x

In [12]:
x_recovered = OMP(A, b, maxit, epsilon)
x_recovered

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.0092992, 0.       , 0.       ])